apiVersion: v1
kind: Secret
metadata:
  name: enigma
type: Opaque
stringData:
  APP_HOST: 'localhost'
  APP_PORT: '13337'
  APP_LOG_LEVEL: 'debug'
  REDIS_PORT: '6379'
  REDIS_HOST: ''
  ENCRYPT_KEY: '0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF'
  ENCRYPT_CACHE_PREFIX: 'enigma:encrypt-cache'
  ENCRYPT_CACHE_TTL: '3600'
