name: Build push and deploy
on: push
  #release:
  #  types: [created]

jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get commit short sha (7)
        id: vars
        run: echo "::set-output name=sha_short::$( echo $GITHUB_SHA | head -c7)"

      - uses: actions/checkout@v3
        name: Check out code

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: behemoth131/enigma:${{ steps.vars.outputs.sha_short }}
    
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Set Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy enigma
        run: |
          helm upgrade --install env .github/helm/env --namespace enigma 
          helm delete enigma --namespace enigma || true
          helm install enigma .github/helm/enigma \
          --set image.tag=${{ steps.vars.outputs.sha_short }} \
          --set image.repository=behemoth131/enigma \
          --namespace enigma 

